os: linux
sudo: required
jdk: oraclejdk8


env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

dist: xenial
addons:
  apt:
    sources:
      - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
        key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

language: android

android:
  components:
    - tools
    - platform-tools-28.0.2
    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional component
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
     - sys-img-armeabi-v7a-android-28
    # if you need to run emulator(s) during your tests
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
    #- touch $HOME/.android/repositories.cfg
    #- yes | sdkmanager "platforms;android-28"
    #- yes | sdkmanager "build-tools;28.0.3"
    - export LANG=en_US.UTF-8
    
before_script:
  # Create and start emulator
   - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script: ./gradlew clean build

script: ./gradlew connectedAndroidTest

